### PR TITLE
Upgrade repo to Go 1.18

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/41)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/41)* status: 0 of 1 LGTMs obtained

___
*[`Dockerfile` line 5 at r1](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/41#-N9Z6ryT-6tfGErjSjhd:-N9Z6ryT-6tfGErjSjhe:b11kmq0) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/195b9c82cf1664092a7f52a083ee0e4916d16fb3/Dockerfile#L5)):*
> ```Dockerfile
> WORKDIR /go/src/github.com/m-lab/prometheus-bigquery-exporter
> RUN go vet && \
>     go get -t . && \
> ```

I'm certain we've encountered issues due to dynamic linking between different base images.. 

When I build the original image, the go binary is dynamically linked with a few libraries that are in both the builder and runtime image.

```
/bin # ldd ./prometheus-bigquery-exporter 
	/lib/ld-musl-x86_64.so.1 (0x7f2122c6c000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f2122c6c000)
```

With this modification the builder and runtime environments are different.

```
/bin # ldd ./prometheus-bigquery-exporter 
	/lib64/ld-linux-x86-64.so.2 (0x7fb83c354000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fb83c354000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fb83c354000)
/bin # ./prometheus-bigquery-exporter -h
/bin/sh: ./prometheus-bigquery-exporter: not found
/bin # 
```

So, some libraries are not found in the alpine environment. The cryptic "not found" message is referring to the "not found" linked libraries.

**Comment by SaiedKazemi** [comment]
*[`Dockerfile` line 5 at r1](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/41#-N9Z6ryT-6tfGErjSjhd:-N9ZDlL1E2c2x3qVv22L:b1bd6ek) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/195b9c82cf1664092a7f52a083ee0e4916d16fb3/Dockerfile#L5)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm certain we've encountered issues due to dynamic linking between different base images.. 

When I build the original image, the go binary is dynamically linked with a few libraries that are in both the builder and runtime image.

```
/bin # ldd ./prometheus-bigquery-exporter 
	/lib/ld-musl-x86_64.so.1 (0x7f2122c6c000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f2122c6c000)
```

With this modification the builder and runtime environments are different.

```
/bin # ldd ./prometheus-bigquery-exporter 
	/lib64/ld-linux-x86-64.so.2 (0x7fb83c354000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fb83c354000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fb83c354000)
/bin # ./prometheus-bigquery-exporter -h
/bin/sh: ./prometheus-bigquery-exporter: not found
/bin # 
```

So, some libraries are not found in the alpine environment. The cryptic "not found" message is referring to the "not found" linked libraries.
</blockquote></details>

Thank you for your comment.  I spent quite a bit of time looking at other `Dockerfile`s in repos that are already using Go 1.18 and made my changes based on what I found.  But I understand from your comment that there is more to this than meet the eye!  Let's chat interactively.

**Comment by SaiedKazemi** [comment]
Thank you for your review @stephen-soltesz .

**Comment by SaiedKazemi** [comment]
*[`Dockerfile` line 5 at r1](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/41#-N9Z6ryT-6tfGErjSjhd:-N9Zkqrq2Nd-hcsuGPhw:b8x2d7s) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/195b9c82cf1664092a7f52a083ee0e4916d16fb3/Dockerfile#L5)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Thank you for your comment.  I spent quite a bit of time looking at other `Dockerfile`s in repos that are already using Go 1.18 and made my changes based on what I found.  But I understand from your comment that there is more to this than meet the eye!  Let's chat interactively.
</blockquote></details>

I added "ENV CGO_ENABLED 0" to disable cgo dynamic linking.  After this change, I made sure that `prometheus-bigquery-exporter` runs:
```
Step 9/11 : RUN /bin/prometheus-bigquery-exporter -h
 ---> Running in ed6269fc5c63
Usage of /bin/prometheus-bigquery-exporter:
  -gauge-query value
    	Name of file containing a gauge query. (default []string{})
  -logx.debug value
    	Enable logx debug logging.
  -project string
    	GCP project name.
  -prometheusx.listen-address string
    	 (default ":9990")
  -refresh duration
    	Interval between updating metrics. (default 5m0s)
```

I think we should prioritize standard build instructions across all our repos.

**Review by stephen-soltesz — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/41)* status: 0 of 1 LGTMs obtained

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/41)* status: 0 of 1 LGTMs obtained

___
*[`Dockerfile` line 12 at r2](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/41#-N9bTSPO1ZwPW4-95tvg:-N9bTSPO1ZwPW4-95tvh:bst887g) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/d63530b23584c031e46fefffdfd8aed8a7c44296/Dockerfile#L12)):*
> ```Dockerfile
> COPY --from=builder /go/bin/prometheus-bigquery-exporter /bin/prometheus-bigquery-exporter
> EXPOSE 9348
> ENTRYPOINT  [ "/bin/prometheus-bigquery-exporter" ]
> ```

In terms of standard steps, what do you think of adding a standard step like `RUN /bin/prometheus-bigquery-exporter -h > /dev/null` that sanity-checks the binary to be able to run enough to print help? This would fail the build if there were ever missing libraries, and even when we build statically, this would make sure we don't forget that.

**Comment by SaiedKazemi** [comment]
*[`Dockerfile` line 12 at r2](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/41#-N9bTSPO1ZwPW4-95tvg:-N9bVhMECbaTGFwJ8ifX:b-9ge1oo) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/d63530b23584c031e46fefffdfd8aed8a7c44296/Dockerfile#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

In terms of standard steps, what do you think of adding a standard step like `RUN /bin/prometheus-bigquery-exporter -h > /dev/null` that sanity-checks the binary to be able to run enough to print help? This would fail the build if there were ever missing libraries, and even when we build statically, this would make sure we don't forget that.
</blockquote></details>

I like the idea and will add the check to all `Dockerfile`s that I will edit for upgrading to Go 1.18.

**Pull request merged**
