### PR TITLE
Update m-lab/go to v0.1.66

### PR DESCRIPTION
**Pull request by robertodauria**
Part of https://github.com/m-lab/dev-tracker/issues/674

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/47)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
Do we know why the build is failing?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/47#-:-Ncgw1UR8ZKcGUyq8M2R:bsiol1h)* status: 0 of 1 LGTMs obtained

**Review by robertodauria — COMMENTED** [review]
Should be fixed now. PTAL again please?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/47#-:-Nch9PaJ6OH3MnXiJW7k:b5lhjaj)* status: 0 of 1 LGTMs obtained

**Review by cristinaleonr — COMMENTED** [review]
Thanks! Does the pull request [build](https://app.travis-ci.com/github/m-lab/prometheus-bigquery-exporter/pull_requests) need to be re-run to pass?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/47#-:-NchC6lrCxm8Sqr7fo4y:b-olt13q)* status: 0 of 1 LGTMs obtained

**Review by robertodauria — COMMENTED** [review]
I tried to restart it, but it's failing due to a 500 coming from coveralls -- not related to this change.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/47#-:-NchDRrS5ZBwXiq97hXG:b-vibzcj)* status: 0 of 1 LGTMs obtained

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/47#-:-NchIh081qckmDXK3GlT:bg7igkv)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
