### PR TITLE
Add bq.Collector implementation

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change completes the `bq` package implementation of the `prometheus.Collector` interface.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/2)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[bq/bq.go, line 12 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2#-Ky1Xt2wVkdIcfvMV20f:-Ky1Xt2wVkdIcfvMV20g:b-httvb5) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/e22756aa6b2f8460b06512563386bb70d722cd33/bq/bq.go#L12)):*
> ```Go
> type Collector struct {
> 	runner QueryRunner
> 	name   string
> ```

metricName ?

---

*[bq/bq.go, line 37 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2#-Ky1Y-MDBoOu-bY2ZDk2:-Ky1Y-MDBoOu-bY2ZDk3:b-a803an) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/e22756aa6b2f8460b06512563386bb70d722cd33/bq/bq.go#L37)):*
> ```Go
> // Describe satisfies the prometheus.Collector interface. Describe is called
> // immediately after registering the collector.
> func (bq *Collector) Describe(ch chan<- *prometheus.Desc) {
> ```

I find it confusing to use bq, which is the package name, and does not suggest that it is a collector.

How about col?  Or reluctantly, just c?  (since the methods are all really short, I can deal with that).

---

*[bq/bq.go, line 51 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2#-Ky1_TfwH4jvx9w6fTQj:-Ky1_TfwH4jvx9w6fTQk:bjzy4a1) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/e22756aa6b2f8460b06512563386bb70d722cd33/bq/bq.go#L51)):*
> ```Go
> func (bq *Collector) Collect(ch chan<- prometheus.Metric) {
> 	bq.mux.Lock()
> 	defer bq.mux.Unlock()
> ```

Probably doesn't matter, but would be faster (in terms of interfering with Update), to copy the slice reference under the lock, then release the lock and use the reference.

---

*[bq/bq.go, line 74 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2#-Ky1Za6AughmqdsBXDxe:-Ky1Za6AughmqdsBXDxf:b9mlmz1) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/e22756aa6b2f8460b06512563386bb70d722cd33/bq/bq.go#L74)):*
> ```Go
> 	bq.mux.Lock()
> 	defer bq.mux.Unlock()
> 	bq.metrics = metrics
> ```

I still have to think carefully (or look stuff up) to remember exactly the semantics of assignment in go.  Very frustrating.

Please add a comment clarifying what this assignment does.  I think we need to reinforce until we are all more familiar with golang semantics.

This assigns the bq.metrics slice reference to point to the new metrics.  References to the previous value of bq.metrics are not affected.

My language for these details is still murky, so feel free to improve.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2)*

**Comment by gfr10598** [comment]
A few readability comments, and one performance comment.
Otherwise looks good.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2#-:-Ky1_evieT7YN-HxnoXt:bnvgexd)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[bq/bq.go, line 12 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2#-Ky1Xt2wVkdIcfvMV20f:-Ky1a_2OQrvzuIGHzPnW:b-896fix) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/e22756aa6b2f8460b06512563386bb70d722cd33/bq/bq.go#L12)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

metricName ?
</blockquote></details>

Done.

---

*[bq/bq.go, line 37 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2#-Ky1Y-MDBoOu-bY2ZDk2:-Ky1aubqEzoU8rBSLWsy:bgednuq) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/e22756aa6b2f8460b06512563386bb70d722cd33/bq/bq.go#L37)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I find it confusing to use bq, which is the package name, and does not suggest that it is a collector.

How about col?  Or reluctantly, just c?  (since the methods are all really short, I can deal with that).
</blockquote></details>

Changed to col.

---

*[bq/bq.go, line 51 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2#-Ky1_TfwH4jvx9w6fTQj:-Ky1cEpHvPtkC7bHC50B:bhqdsgb) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/e22756aa6b2f8460b06512563386bb70d722cd33/bq/bq.go#L51)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Probably doesn't matter, but would be faster (in terms of interfering with Update), to copy the slice reference under the lock, then release the lock and use the reference.
</blockquote></details>

Ooh. Good point! Done.

---

*[bq/bq.go, line 74 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2#-Ky1Za6AughmqdsBXDxe:-Ky1cllQY0-G_28T1N08:b44c8af) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/e22756aa6b2f8460b06512563386bb70d722cd33/bq/bq.go#L74)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I still have to think carefully (or look stuff up) to remember exactly the semantics of assignment in go.  Very frustrating.

Please add a comment clarifying what this assignment does.  I think we need to reinforce until we are all more familiar with golang semantics.

This assigns the bq.metrics slice reference to point to the new metrics.  References to the previous value of bq.metrics are not affected.

My language for these details is still murky, so feel free to improve.
</blockquote></details>

No problem. I've added a comment adapted from your feedback.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2)*

**Comment by gfr10598** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/2#-:-Ky2GGbNUnKbUIi_LzVs:bnfp4nl)*

**Pull request merged**
