### PR TITLE
Add supporting interfaces for the bigquery collector package

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a support package for the bigquery prometheus Collector interface. This change only includes the definition of the QueryRunner interface and supporting functions.

This change also adds documentation to the README to outline usage of the exporter. And, this change adds basic .travis.yml configuration with Go coverage.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/1)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[README.md, line 16 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-KxwzuaXJrZO2sUaJf4V:-KxwzuaYoi1MTf5DzHyO:b7zb15d) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/README.md#L16)):*
> ```Markdown
> 
> So, the results of queries run by prometheus-bigquery-exporter should represent
> a meaningful value at a fixed point in time, e.g. total number of tests in a 5
> ```

a fixed point in time relative to the time the query is made, ...

---

*[README.md, line 27 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx07W_BZI7R6w62oiF:-Kxx07W_BZI7R6w62oiG:b-qumin6) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/README.md#L27)):*
> ```Markdown
> Required columns:
> 
>  * `value` -- every query result must have a "value". If there is more than one
> ```

... a "value" column.

I would move the next sentence down to introduce the Optional columns section.

---

*[README.md, line 50 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx0SWa8Qdxg2fCfg-D:-Kxx0SWa8Qdxg2fCfg-E:b-nijam2) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/README.md#L50)):*
> ```Markdown
> SELECT
>     -- All metric labels should have a column name prefixed with "label_"
>     CONCAT(REPLACE(REGEXP_EXTRACT(task_filename,
> ```

How would you think about using views to simplify some of this.  We could have a dataset specifically for exporter related views.

---

*[README.md, line 58 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx0flE_fpWpPyj7JlN:-Kxx0flE_fpWpPyj7JlO:b-8kyru) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/README.md#L58)):*
> ```Markdown
> 
> FROM
>     [measurement-lab:public.ndt]
> ```

Please use #standardSQL and `measurement-lab.public.ndt`.  I'd like us to avoid legacy as much as possible.

---

*[bq/query_runner.go, line 17 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx1kwFl8DDBVZBL6vk:-Kxx1kwFl8DDBVZBL6vl:b-99r8q1) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L17)):*
> ```Go
> )
> 
> // QueryRunner defines the interface used to run a query and return an array of metrics.
> ```

// TODO - move these to api package when they need to be shared with other QueryRunner impls.

---

*[bq/query_runner.go, line 29 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx1IoZI0m473maC574:-Kxx1IoZI0m473maC575:bpaurz0) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L29)):*
> ```Go
> }
> 
> // queryRunnerImpl is a concerete implementation of QueryRunner for BigQuery.
> ```

BTW: Nice use of  abstract/concrete!

---

*[bq/query_runner.go, line 38 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx1zc8YL6fIJFsnYe4:-Kxx1zc8YL6fIJFsnYe5:b-3yhylt) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L38)):*
> ```Go
> 	return &queryRunnerImpl{client}
> }
> ```

will continue reviewing here shortly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1)*

**Comment by gfr10598** [comment]
BTW, very nice design!

---

Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-:-Kxx24S4HSFGSX8IYXPO:btyjzli)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[bq/query_runner.go, line 39 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx8Kr3T7mVWASLHX_U:-Kxx8Kr3T7mVWASLHX_V:b-171wkg) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L39)):*
> ```Go
> }
> 
> // Query executes the given query. Currently only Legacy SQL is supported. The
> ```

Hmm - why legacy SQL?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[bq/query_runner.go, line 48 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx8oHHlIuJ_uvk9ucW:-Kxx8oHHlIuJ_uvk9ucX:bi3gzlw) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L48)):*
> ```Go
> 
> 	// TODO: check query string for SQL type.
> 	q.QueryConfig.UseStandardSQL = false
> ```

FYI, doc says standard is the default, and UseStandardSQL is deprecated.  UseLegacySQL instead.

---

*[bq/query_runner.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx98vgEmamx8ELNI6f:-Kxx98vgEmamx8ELNI6g:b-9uilpi) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L53)):*
> ```Go
> 	it, err := q.Read(context.Background())
> 	if err != nil {
> 		log.Print(err)
> ```

Please enable the file/linenum formatting for logger.

```go
func init() {
	// Always prepend the filename and line number.
	log.SetFlags(log.LstdFlags | log.Lshortfile)
}
```

---

*[bq/query_runner.go, line 74 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx9tEYQBE-S3pZeDRA:-Kxx9tEYQBE-S3pZeDRB:bare2d3) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L74)):*
> ```Go
> // valToFloat extracts a float from the bigquery.Value irrespective of the
> // underlying type. If the type is not int64, float64, then valToFloat returns
> // zero.
> ```

nit: Perhaps return NaN if invalid?

---

*[bq/query_runner.go, line 88 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-KxxAbzWkqsc_gkCnImn:-KxxAbzWkqsc_gkCnImo:b-kbhsy6) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L88)):*
> ```Go
> // valToString coerces the bigquery.Value into a string. If the underlying type
> // is not a string, we treat it like an int64 or float64. If the underlying is
> // none of these types, valToString returns "0".
> ```

nit: return "invalid string" ?

Actually, should these result in a warning metric increment or log?

---

*[bq/query_runner.go, line 110 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-KxxBLObIG6JF4cyl1sr:-KxxBLObIG6JF4cyl1ss:b-70vnus) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L110)):*
> ```Go
> 	for k, v := range row {
> 		if strings.HasPrefix(k, "label_") {
> 			m.labels = append(m.labels, strings.TrimPrefix(k, "label_"))
> ```

Trimming and then later adding the label_ prefix seems unnecessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1)*

**Comment by gfr10598** [comment]
LGTM - looks Great!

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-:-KxxBUXsLtXoDsBGCFqb:b-6at8x2)*

**Comment by stephen-soltesz** [comment]
Review status: 1 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[README.md, line 16 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-KxwzuaXJrZO2sUaJf4V:-Kxy15r29F4QwNiL8KtI:b-cz3gvp) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/README.md#L16)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

a fixed point in time relative to the time the query is made, ...
</blockquote></details>

Yes, that helps. Done.

---

*[README.md, line 27 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx07W_BZI7R6w62oiF:-Kxyd9wZdpflDJT9Orxz:b-896fix) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/README.md#L27)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

... a "value" column.

I would move the next sentence down to introduce the Optional columns section.
</blockquote></details>

Done.

---

*[README.md, line 50 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx0SWa8Qdxg2fCfg-D:-KxyMmNpmIIjqsbnbhlU:b-jq1d05) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/README.md#L50)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

How would you think about using views to simplify some of this.  We could have a dataset specifically for exporter related views.
</blockquote></details>

Sounds good to me.

TODO added.

---

*[README.md, line 58 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx0flE_fpWpPyj7JlN:-KxyMrb8i8rQELkaAwfC:b-7b8x0q) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/README.md#L58)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please use #standardSQL and `measurement-lab.public.ndt`.  I'd like us to avoid legacy as much as possible.
</blockquote></details>

Yes. My initial use case involved using the `CASE` expression to distinguish between c2s and s2c counts. Standard didn't have that and (having not yet investigated carefully) I'm not sure how to do the equivalent operation yet with standard. I agree that adopting standard sql only is the right thing.

TODO added.

---

*[bq/query_runner.go, line 17 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx1kwFl8DDBVZBL6vk:-KxyNxoS24SszvLeuEsm:b-gpegm2) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L17)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

// TODO - move these to api package when they need to be shared with other QueryRunner impls.
</blockquote></details>

Tests in an upcoming PR use a fake implementation, but I don't anticipate any other implementations. Do you have a use case in mind?

---

*[bq/query_runner.go, line 29 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx1IoZI0m473maC574:-KxyODcOyFhb7_fkqw0K:b-8fx2u7) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L29)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

BTW: Nice use of  abstract/concrete!
</blockquote></details>

:+1: 

---

*[bq/query_runner.go, line 39 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx8Kr3T7mVWASLHX_U:-KxyOKGRYHIBHzorpRRu:bdor1to) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L39)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Hmm - why legacy SQL?
</blockquote></details>

My initial motivating query used `CASE` statements. I agree that only supporting standard sql is preferable.

---

*[bq/query_runner.go, line 48 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx8oHHlIuJ_uvk9ucW:-KxyPEaKME3Pm-3_eqyf:bj44tic) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L48)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

FYI, doc says standard is the default, and UseStandardSQL is deprecated.  UseLegacySQL instead.
</blockquote></details>

Yes, but that only happened a day ago :-) https://github.com/GoogleCloudPlatform/google-cloud-go/releases/tag/v0.16.0

Changed.

Changed TODO to only support Standard SQL.

---

*[bq/query_runner.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx98vgEmamx8ELNI6f:-KxyPNeYstj7Q5AOrVz4:b5pbb3l) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L53)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please enable the file/linenum formatting for logger.

```go
func init() {
	// Always prepend the filename and line number.
	log.SetFlags(log.LstdFlags | log.Lshortfile)
}
```
</blockquote></details>

I think this should be set from main or the tests? Otherwise, it's unclear to me how to prevent different packages from resetting these flags.

---

*[bq/query_runner.go, line 74 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-Kxx9tEYQBE-S3pZeDRA:-KxyQ8-hwrLo3PI327uW:b-s3exlt) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L74)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

nit: Perhaps return NaN if invalid?
</blockquote></details>

Good idea. That hadn't occurred to me. I just checked and I think prometheus does the right thing with NaN.

Changed.

---

*[bq/query_runner.go, line 88 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-KxxAbzWkqsc_gkCnImn:-Kxyc6Xw_qn85qXP6ILl:b-j2imkv) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L88)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

nit: return "invalid string" ?

Actually, should these result in a warning metric increment or log?
</blockquote></details>

I like the idea of using "invalid string" because this is almost certainly not what a user would want and when they see that in the metrics they'll fix it.

Regarding logging, I'm worried this would happen too frequently and spam the logs or add complexity. We could add a metric that counts these, but I like the idea of relying on the value not being what the user expects e.g. "invalid string".

Changed.

---

*[bq/query_runner.go, line 110 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-KxxBLObIG6JF4cyl1sr:-KxyZ8jWFx46CUb7quD8:b-ed718i) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/47494acf4a0209320d60d536b8588672c158a0f4/bq/query_runner.go#L110)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Trimming and then later adding the label_ prefix seems unnecessary.
</blockquote></details>

Yeah, as I was writing the README I wondered I should just treat every column not named "value" as a label. Let's drop the "label_" prefix requirement.

Updated this logic and the README to drop the "label_" prefix requirement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1)*

**Comment by stephen-soltesz** [comment]
Merging now and will happily address any outstanding issues in subsequent PRs.

**Comment by gfr10598** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-bigquery-exporter/1#-:-KxyfNuDPliaS8vnMzsK:bnfp4nl)*

**Pull request merged**
