### PR TITLE
Fix docker image build using versioned dependencies

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change updates the `Dockerfile` to use pinned alpine container images and updates the go version to 1.18.

This change also fixes a typo in the README.md for running a sample command.

Fixes https://github.com/m-lab/prometheus-bigquery-exporter/issues/37

Tested locally using the steps in the README. Does not produce error reported in #37.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/38)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
*[Dockerfile, line 8 at r1](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/38#-N07Jub544lxqFleME7e:-N07Jub544lxqFleME7f:b-uo2bg8) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/1fa5878a9b9f6d90d15901a2e73b20487837ea0c/Dockerfile#L8)):*
> ```Dockerfile
> RUN go get -t .
> RUN go install .
> ```

I think Dockerfile best practices suggest that multiple RUN commands be merged into a single one to avoid creating filesystem layers when they're not needed.

**Review by SaiedKazemi — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/38)* status: 0 of 1 LGTMs obtained

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/38)* status: 0 of 1 LGTMs obtained

___
*[Dockerfile, line 8 at r1](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/38#-N07Jub544lxqFleME7e:-N07tSsk0wS6o5uKXf1w:bi0z8qm) ([raw file](https://github.com/m-lab/prometheus-bigquery-exporter/blob/1fa5878a9b9f6d90d15901a2e73b20487837ea0c/Dockerfile#L8)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I think Dockerfile best practices suggest that multiple RUN commands be merged into a single one to avoid creating filesystem layers when they're not needed.
</blockquote></details>

Thank you. I knew I'd get good feedback. I've combined all the `go` commands. I've preserved separation between the different kind of operations (i.e. adding packages vs building sources). How does that look?

**Comment by SaiedKazemi** [comment]
:lgtm:

**Review by SaiedKazemi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-bigquery-exporter/38)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
